### ISSUE TITLE
About performance reproducing

### ISSUE THREAD

**Issue by ChanhuiLee1111** [RandolphCarter0/TRMUAP#4]
Hello, thanks for your interesting work.
I tried to reproduce your code with your best setting with VGG16, but the ASR into resnet152 is 53 (in your paper, 61). Also, the given UAP-VGG16's ASR is  in ./perturbations is 58. Is there anything that I couldn't consider?

**Comment by RandolphCarter0** [comment]
Hi, thank you for your interest in our work. 
In the experiments of transferability, the performance of UAP is the average from repeated experiments with variance, rather than the result of a specific experiment. The ASR is different because of the various architectures of models. As we said in readme, you can check your set of curriculum learning strategies and seeds to explore better performance.
